#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
  path: /
  controller: App\Controller\HomeController::index

app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number

blog_show:
  path: /blog/{page}
  controller: app\Controller\BlogController::show
  defaults:
    page: 'Article Sans Titre'
  requirements:
    slug: '[A-Za-z0-9\-]+'
